BORED_ROW = 25
BORED_COL = 50
NO_MINE = "EMPTY"
BLACK = (59 , 59, 59 )
GREEN = (107,142,35)
WINDOW_WIDTH = 500
WINDOW_HEIGHT = 250

WIN_MESSAGE = "YOU WON!"
WIN_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
WIN_COLOR = BLACK
WIN_LOCATION = (0.2 * WINDOW_WIDTH , WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))
FONT_NAME = "Calibri"
LOSE_MESSAGE = "YOU LOST :( "
LOSE_FONT_SIZE = WIN_FONT_SIZE
LOSE_COLOR = BLACK
LOSE_LOCATION = (0.2 * WINDOW_WIDTH , WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))

FLAG_IMG = "flag.png"
FLAG_HEIGHT = 40
FLAG_WIDTH = 30
FLAG_X = WINDOW_WIDTH - FLAG_WIDTH
FLAG_Y = WINDOW_HEIGHT - FLAG_HEIGHT

SOLDIER_IMG = "soldier.png"
SOLDIER_LEGS_HEIGHT = 10
SOLDIER_BODY_HEIGHT = 30
SOLDIER_HEIGHT = SOLDIER_LEGS_HEIGHT  + SOLDIER_BODY_HEIGHT
SOLDIER_WIDTH = 20
SOLDIER_LEGS_WIDTH = SOLDIER_WIDTH
SOLDIER_BODY_WIDTH = SOLDIER_WIDTH
SOLDIER_X = WINDOW_WIDTH - SOLDIER_WIDTH
SOLDIER_Y = WINDOW_HEIGHT - SOLDIER_HEIGHT


SOLDIER_NIGHT_IMG = "soldier.png"
SOLDIER_NIGHT_HEIGHT = 40
SOLDIER_NIGHT_WIDTH = 20
SOLDIER_NIGHT_X = WINDOW_WIDTH - SOLDIER_NIGHT_WIDTH
SOLDIER_NIGHT_Y = WINDOW_HEIGHT - SOLDIER_NIGHT_HEIGHT

GRASS_IMG = "grass.png"
GRASS_HEIGHT = 10
GRASS_WIDTH = 30
GRASS_X = WINDOW_WIDTH - GRASS_WIDTH
GRASS_Y = WINDOW_HEIGHT - GRASS_HEIGHT

MINE_IMG = "mine.png"
MINE_HEIGHT = 10
MINE_WIDTH = 30
MINE_X = WINDOW_WIDTH - MINE_WIDTH
MINE_Y = WINDOW_HEIGHT - MINE_HEIGHT

RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3

